import { Listing, Inquiry } from './types';

export const MOCK_LISTINGS: Listing[] = [
  {
    id: 'lot-001',
    sellerId: 'seller-001',
    title: 'Prime Residential Lot in Jaro, Iloilo City',
    description:
      'Flat, ready-to-build residential lot in a quiet subdivision in Brgy. Dungon-A, Jaro. Walking distance to Jaro Cathedral, schools, and wet market. Perfect for OFW families looking to build their dream home close to city conveniences. Concrete road frontage with existing perimeter fence on two sides.',
    province: 'Iloilo City',
    municipality: 'Jaro',
    barangay: 'Dungon-A',
    polygon: [
      { lat: 10.71987, lng: 122.56243 },
      { lat: 10.71987, lng: 122.56257 },
      { lat: 10.71973, lng: 122.56257 },
      { lat: 10.71973, lng: 122.56243 },
    ],
    center: { lat: 10.7198, lng: 122.5625 },
    areaSqm: 250,
    pricePHP: 2500000,
    titleType: 'TCT',
    zoning: 'Residential',
    roadAccess: 'Concrete barangay road, 6m wide',
    utilities: ['Electricity (MORE Power)', 'Water (Metro Iloilo)', 'Internet (PLDT/Converge)'],
    elevation: 8,
    hazardFlags: [],
    boundaryConfidence: 'survey-based',
    status: 'available',
    photos: [],
    documents: [
      { type: 'title', available: true, label: 'Transfer Certificate of Title' },
      { type: 'tax_declaration', available: true, label: 'Tax Declaration (2025)' },
      { type: 'lot_plan', available: true, label: 'Lot Plan / Sketch' },
      { type: 'survey', available: true, label: 'Geodetic Survey' },
      { type: 'deed_of_sale', available: false, label: 'Deed of Absolute Sale' },
    ],
    createdAt: '2026-03-15T08:00:00Z',
    updatedAt: '2026-04-01T10:30:00Z',
  },
  {
    id: 'lot-002',
    sellerId: 'seller-002',
    title: 'Spacious Agricultural Lot in Oton',
    description:
      'Productive agricultural land in Brgy. Trapiche, Oton. Currently planted with mango and coconut trees. Ideal for farming, agri-tourism, or future residential development as the area is rapidly urbanizing. Just 15 minutes from SM City Iloilo. Great long-term investment for overseas Ilonggos wanting to keep roots in the province.',
    province: 'Iloilo',
    municipality: 'Oton',
    barangay: 'Trapiche',
    polygon: [
      { lat: 10.6926, lng: 122.4741 },
      { lat: 10.6926, lng: 122.4749 },
      { lat: 10.6920, lng: 122.4751 },
      { lat: 10.6918, lng: 122.4745 },
      { lat: 10.6921, lng: 122.4740 },
    ],
    center: { lat: 10.6924, lng: 122.4745 },
    areaSqm: 2000,
    pricePHP: 1800000,
    titleType: 'Tax Declaration',
    zoning: 'Agricultural',
    roadAccess: 'Gravel barangay road, 4m wide',
    utilities: ['Electricity (MORE Power)'],
    elevation: 12,
    hazardFlags: ['Flood-prone during heavy typhoons'],
    boundaryConfidence: 'approximate',
    status: 'available',
    photos: [],
    documents: [
      { type: 'title', available: false, label: 'Transfer Certificate of Title' },
      { type: 'tax_declaration', available: true, label: 'Tax Declaration (2025)' },
      { type: 'lot_plan', available: true, label: 'Lot Plan / Sketch' },
      { type: 'survey', available: false, label: 'Geodetic Survey' },
      { type: 'deed_of_sale', available: false, label: 'Deed of Absolute Sale' },
    ],
    createdAt: '2026-02-20T06:00:00Z',
    updatedAt: '2026-03-28T14:00:00Z',
  },
  {
    id: 'lot-003',
    sellerId: 'seller-003',
    title: 'Commercial Corner Lot in Pavia',
    description:
      'High-visibility corner lot along the national highway in Brgy. Aganan, Pavia. Zoned commercial with steady foot traffic from nearby schools and the public market. Ideal for a convenience store, pharmacy, or small commercial building. Fully titled with clean documentation — hassle-free transfer for buyers abroad.',
    province: 'Iloilo',
    municipality: 'Pavia',
    barangay: 'Aganan',
    polygon: [
      { lat: 10.77428, lng: 122.54131 },
      { lat: 10.77428, lng: 122.54149 },
      { lat: 10.77414, lng: 122.54149 },
      { lat: 10.77411, lng: 122.54140 },
      { lat: 10.77414, lng: 122.54131 },
    ],
    center: { lat: 10.7742, lng: 122.5414 },
    areaSqm: 350,
    pricePHP: 4200000,
    titleType: 'TCT',
    zoning: 'Commercial',
    roadAccess: 'National highway frontage, concrete, 2-lane',
    utilities: ['Electricity (MORE Power)', 'Water (Metro Iloilo)', 'Internet (PLDT/Converge/Globe)'],
    elevation: 10,
    hazardFlags: [],
    boundaryConfidence: 'survey-based',
    status: 'reserved',
    photos: [],
    documents: [
      { type: 'title', available: true, label: 'Transfer Certificate of Title' },
      { type: 'tax_declaration', available: true, label: 'Tax Declaration (2025)' },
      { type: 'lot_plan', available: true, label: 'Lot Plan / Sketch' },
      { type: 'survey', available: true, label: 'Geodetic Survey' },
      { type: 'deed_of_sale', available: false, label: 'Deed of Absolute Sale' },
    ],
    createdAt: '2026-01-10T09:00:00Z',
    updatedAt: '2026-04-05T16:00:00Z',
  },
  {
    id: 'lot-004',
    sellerId: 'seller-001',
    title: 'Hilltop Lot with View in Santa Barbara',
    description:
      'Elevated residential lot in Brgy. Balabag, Santa Barbara with panoramic views of the Iloilo plains and distant mountains. Peaceful neighborhood away from city noise but only 20 minutes to Iloilo City proper. Slight slope — perfect for a split-level home design. Neighbors have already built modern houses in the area.',
    province: 'Iloilo',
    municipality: 'Santa Barbara',
    barangay: 'Balabag',
    polygon: [
      { lat: 10.82210, lng: 122.53460 },
      { lat: 10.82210, lng: 122.53480 },
      { lat: 10.82196, lng: 122.53483 },
      { lat: 10.82190, lng: 122.53473 },
      { lat: 10.82194, lng: 122.53460 },
    ],
    center: { lat: 10.8220, lng: 122.5347 },
    areaSqm: 500,
    pricePHP: 1500000,
    titleType: 'OCT',
    zoning: 'Residential',
    roadAccess: 'Concrete barangay road, 5m wide',
    utilities: ['Electricity (MORE Power)', 'Water (Level III deepwell)'],
    elevation: 45,
    hazardFlags: [],
    boundaryConfidence: 'approximate',
    status: 'available',
    photos: [],
    documents: [
      { type: 'title', available: true, label: 'Original Certificate of Title' },
      { type: 'tax_declaration', available: true, label: 'Tax Declaration (2024)' },
      { type: 'lot_plan', available: false, label: 'Lot Plan / Sketch' },
      { type: 'survey', available: false, label: 'Geodetic Survey' },
      { type: 'deed_of_sale', available: false, label: 'Deed of Absolute Sale' },
    ],
    createdAt: '2026-03-01T07:00:00Z',
    updatedAt: '2026-03-20T11:00:00Z',
  },
  {
    id: 'lot-005',
    sellerId: 'seller-004',
    title: 'Beachside Lot near Roxas City',
    description:
      'Rare residential lot just 200 meters from the shoreline in Brgy. Baybay, Roxas City. Gentle sea breeze, sandy soil, and coconut-lined surroundings. Walk to the famous Baybay Beach seafood strip. Ideal for a vacation home or rental property catering to local tourism. Title is clean and ready for transfer.',
    province: 'Capiz',
    municipality: 'Roxas City',
    barangay: 'Baybay',
    polygon: [
      { lat: 11.58526, lng: 122.75124 },
      { lat: 11.58526, lng: 122.75136 },
      { lat: 11.58515, lng: 122.75137 },
      { lat: 11.58514, lng: 122.75125 },
    ],
    center: { lat: 11.5852, lng: 122.7513 },
    areaSqm: 150,
    pricePHP: 975000,
    titleType: 'TCT',
    zoning: 'Residential',
    roadAccess: 'Concrete municipal road, 8m wide',
    utilities: ['Electricity (CAPELCO)', 'Water (Roxas City Water District)', 'Internet (Globe/PLDT)'],
    elevation: 3,
    hazardFlags: ['Storm surge risk zone', 'Coastal erosion advisory'],
    boundaryConfidence: 'survey-based',
    status: 'sold',
    photos: [],
    documents: [
      { type: 'title', available: true, label: 'Transfer Certificate of Title' },
      { type: 'tax_declaration', available: true, label: 'Tax Declaration (2025)' },
      { type: 'lot_plan', available: true, label: 'Lot Plan / Sketch' },
      { type: 'survey', available: true, label: 'Geodetic Survey' },
      { type: 'deed_of_sale', available: true, label: 'Deed of Absolute Sale' },
    ],
    createdAt: '2025-12-05T05:00:00Z',
    updatedAt: '2026-03-10T09:00:00Z',
  },
];

export const MOCK_INQUIRIES: Inquiry[] = [
  {
    id: 'inq-001',
    listingId: 'lot-001',
    buyerName: 'Maria Santos',
    buyerPhone: '+971501234567',
    buyerEmail: 'maria.santos@gmail.com',
    message:
      'Hi, I am an OFW based in Dubai. I am interested in this lot for my retirement home. Can you send me more photos and the exact location pin? Also, is installment payment possible? Thank you.',
    status: 'new',
    createdAt: '2026-04-08T14:00:00Z',
  },
  {
    id: 'inq-002',
    listingId: 'lot-003',
    buyerName: 'Roberto Dela Cruz',
    buyerPhone: '+6591234567',
    buyerEmail: 'roberto.dc@yahoo.com',
    message:
      'Good day. I want to put up a small sari-sari store and pharmacy. Is the lot still available? My wife in Pavia can visit the site. What documents do I need to prepare for the transfer?',
    status: 'responded',
    createdAt: '2026-04-02T09:30:00Z',
  },
  {
    id: 'inq-003',
    listingId: 'lot-004',
    buyerName: 'Jennifer Gonzales',
    buyerPhone: '+821012345678',
    buyerEmail: 'jen.gonzales@hotmail.com',
    message:
      'Interested in the Santa Barbara lot. Can my parents visit and take a video? Also, how much is the real property tax per year? Is there a homeowners association?',
    status: 'new',
    createdAt: '2026-04-10T03:00:00Z',
  },
];
